---
- name: Perform Windows Update Patch Management
  hosts: 172.16.0.67
  tasks:
    - name: Check for available updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - FeaturePacks
          - ServicePacks
        state: searched
        reboot: yes
        reboot_timeout: 3600
      register: updates_list
